version: v0.0.0
server_config:
  servers:
  - name: meta-rest
    host: 127.0.0.1
    port: 8080
    mode: REST
    probe_wait_time: 3s
    http:
      shutdown_duration: 5s
      handler_timeout: 5s
      idle_timeout: 2s
      read_header_timeout: 1s
      read_timeout: 1s
      write_timeout: 1s
  - name: meta-grpc
    host: 127.0.0.1
    port: 8082
    mode: GRPC
    probe_wait_time: "3s"
    grpc:
      max_receive_message_size: 0
      max_send_message_size: 0
      initial_window_size: 0
      initial_conn_window_size: 0
      keepalive:
        max_idle_conn_idle: O
        max_conn_age: ""
        max_conn_age_grace: ""
        time: ""
        timeout: ""
      write_buffer_size: 0
      read_buffer_size: 0
      connection_timeout: ""
      max_header_list_size: 0
      header_table_size: 0
      interceptors: []
    restart: true
  health_check_servers:
  - name: liveness
    host: 127.0.0.1
    port: 3000
    mode: ""
    probe_wait_time: "3s"
    http:
      shutdown_duration: "5s"
      handler_timeout: ""
      idle_timeout: ""
      read_header_timeout: ""
      read_timeout: ""
      write_timeout: ""
  - name: readiness
    host: 127.0.0.1
    port: 3001
    mode: ""
    probe_wait_time: "3s"
    http:
      shutdown_duration: "5s"
      handler_timeout: ""
      idle_timeout: ""
      read_header_timeout: ""
      read_timeout: ""
      write_timeout: ""
  metrics_servers:
  - name: pprof
    host: 127.0.0.1
    port: 6060
    mode: REST
    probe_wait_time: 3s
    http:
      shutdown_duration: 5s
      handler_timeout: 5s
      idle_timeout: 2s
      read_header_timeout: 1s
      read_timeout: 1s
      write_timeout: 1s
  startup_strategy:
  - livenesss
  - pprof
  - meta-grpc
  - meta-rest
  - readiness
  shutdown_strategy:
  - readiness
  - meta-rest
  - meta-grpc
  - pprof
  - livenesss
  full_shutdown_duration: 600s
  tls:
    enabled: false
    cert: /path/to/cert
    key: /path/to/key
    ca: /path/to/ca
redis_config:
  addrs:
  - redis.default.svc.cluster.local
  db: 0
  dial_timeout: ""
  idle_check_frequency: ""
  idle_timeout: ""
  key_pref: ""
  max_conn_age: ""
  max_redirects: 3576761500725386172
  max_retries: 1129817566512326117
  max_retry_backoff: ĒĂ蹨ſɔ鮮豔5>鍵渏餢8ƌF
  min_idle_conns: -1508037936644845558
  min_retry_backoff: ;
  password: ""
  pool_size: -2588166923414328810
  pool_timeout: ò錟ġ@琻r/黩Ƃ貅
  read_only: false
  read_timeout: Ǐ飀7ɉIʀ
  route_by_latency: false
  route_randomly: false
  tls:
    enabled: false
    cert: /path/to/cert
    key: /path/to/key
    ca: /path/to/ca
  tcp:
    dns:
      cache_enabled: false
      refresh_duration: ""
      cache_expiration: ""
    dialer:
      timeout: ""
      keep_alive: ""
      dual_stack_enabled: true
    tls:
      enabled: false
      cert: /path/to/cert
      key: /path/to/key
      ca: /path/to/ca
  write_timeout: ""
  kv_prefix: ""
  vk_prefix: ""
  prefix_delimiter: "

